[package]
name = "kaguya-web"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.14.2"
tonic-prost = "0.14.2"
prost = "0.14.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
axum = "0.8"
tower-http = { version = "0.6", features = ["fs"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
sha2 = "0.10"
rand = "0.8"

[build-dependencies]
tonic-prost-build = "0.14.2"
